### ISSUE TITLE
Feed fails on second request

### ISSUE THREAD

**Issue by gavincabbage** [gavincabbage/johnny5#1]
The feed fails with the following output when the test page is refreshed.

```
[2015-08-28 13:26:51 +0000] [12158] [INFO] Starting gunicorn 19.3.0
[2015-08-28 13:26:51 +0000] [12158] [INFO] Listening at: http://0.0.0.0:9090 (12158)
[2015-08-28 13:26:51 +0000] [12158] [INFO] Using worker: sync
[2015-08-28 13:26:51 +0000] [12163] [INFO] Booting worker with pid: 12163
[2015-08-28 13:26:51 +0000] [12164] [INFO] Booting worker with pid: 12164
mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/johnny/johnny5/feed/camera.py", line 66, in _thread
    with picamera.PiCamera() as camera:
  File "/home/johnny/johnny5/feed/venv/local/lib/python2.7/site-packages/picamera/camera.py", line 488, in __init__
    self.STEREO_MODES[stereo_mode], stereo_decimate)
  File "/home/johnny/johnny5/feed/venv/local/lib/python2.7/site-packages/picamera/camera.py", line 620, in _init_camera
    prefix="Camera component couldn't be enabled")
  File "/home/johnny/johnny5/feed/venv/local/lib/python2.7/site-packages/picamera/exc.py", line 191, in mmal_check
    raise PiCameraMMALError(status, prefix)
PiCameraMMALError: Camera component couldn't be enabled: Out of resources (other than memory)

^C[2015-08-28 13:28:32 +0000] [12158] [INFO] Handling signal: int
[2015-08-28 13:28:32 +0000] [12164] [INFO] Worker exiting (pid: 12164)
[2015-08-28 13:28:32 +0000] [12163] [INFO] Worker exiting (pid: 12163)
^C^C^C[2015-08-28 13:29:02 +0000] [12158] [INFO] Shutting down: Master
```

**Comment by gavincabbage** [comment]
Trying some things found here http://raspberrypi.stackexchange.com/questions/13764/what-causes-enospc-error-when-using-the-raspberry-pi-camera-module

**Comment by gavincabbage** [comment]
The `gpu_mem` option was already 128, so tried running `sudo rpi-update` to update firmware. Didn't work... Increasing `gpu_mem` to 256 for shits and giggles.

**Comment by gavincabbage** [comment]
Changing the number of `gunicorn` worker threads to 1 solved the problem, and upping `gpu_mem` seems to have increased performance a bit as a bonus
